# Generated by Django 5.1.4 on 2025-01-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanoramaImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, max_length=256, null=True, upload_to='img/')),
            ],
            options={
                'db_table': 'panorama_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PanoramaVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('datetime', models.DateField(auto_now=True)),
                ('video', models.FileField(blank=True, max_length=256, null=True, upload_to='video/')),
            ],
            options={
                'db_table': 'panorama_video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=256, verbose_name='장소')),
                ('tree_type', models.CharField(max_length=256, verbose_name='수종')),
                ('tree_num', models.IntegerField(verbose_name='수목')),
                ('diameter', models.FloatField(verbose_name='흉고직경')),
                ('tree_height', models.FloatField(verbose_name='수고')),
                ('crown_width', models.FloatField(verbose_name='수관폭')),
                ('tree_use', models.CharField(max_length=256, verbose_name='사용기종')),
                ('worker_type', models.CharField(max_length=256, verbose_name='측정자 소속')),
                ('worker_name', models.CharField(max_length=256, verbose_name='측정자 성명')),
                ('front_image', models.ImageField(blank=True, max_length=256, null=True, upload_to='tree/')),
                ('north_image', models.ImageField(blank=True, max_length=256, null=True, upload_to='tree/')),
                ('south_image', models.ImageField(blank=True, max_length=256, null=True, upload_to='tree/')),
                ('east_image', models.ImageField(blank=True, max_length=256, null=True, upload_to='tree/')),
                ('west_image', models.ImageField(blank=True, max_length=256, null=True, upload_to='tree/')),
                ('x', models.DecimalField(decimal_places=6, max_digits=8)),
                ('y', models.DecimalField(decimal_places=6, max_digits=8)),
                ('z', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
            options={
                'db_table': 'type_info',
                'managed': False,
            },
        ),
    ]
