# Generated by Django 5.0.3 on 2024-11-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_panoramaimage_panoramavideo_delete_panorama'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panoramaimage',
            options={'managed': True},
        ),
    ]
