# Generated by Django 5.0.3 on 2024-11-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_panoramaimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panoramaimage',
            options={'managed': True},
        ),
    ]
