# Generated by Django 5.0.3 on 2024-11-27 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_panoramaimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='panoramaimage',
            name='video',
            field=models.ForeignKey(db_column='video_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='map.panoramavideo'),
            preserve_default=False,
        ),
    ]
