# Generated by Django 5.0.3 on 2024-11-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_panoramaimage_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panoramaimage',
            old_name='video',
            new_name='video_id',
        ),
    ]
