# Generated by Django 5.1.4 on 2025-02-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('x', models.DecimalField(decimal_places=3, max_digits=8)),
                ('y', models.DecimalField(decimal_places=3, max_digits=8)),
                ('datetime', models.DateTimeField()),
                ('stamptime', models.IntegerField()),
            ],
            options={
                'db_table': 'sensor',
                'managed': False,
            },
        ),
    ]
