# Generated by Django 5.1.4 on 2025-01-23 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 23, 7, 54, 57, 513517, tzinfo=datetime.timezone.utc), help_text='비밀번호 만료 시간'),
        ),
    ]
