# Generated by Django 5.1.4 on 2025-02-11 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_password_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 12, 35, 19, 510269, tzinfo=datetime.timezone.utc), help_text='비밀번호 만료 시간'),
        ),
    ]
